version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fundsroom-backend
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - NODE_ENV=production
      - DATABASE_URL=postgresql://neondb_owner:npg_fLYP2ZFDBd6Q@ep-broad-scene-azmop5qt.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
      - JWT_SECRET=fundsroom-jwt-3f48a1dbe2b75a1c0d48ff99c4d96a782b1c4e97
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fundsroom-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always
