version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fundsroom-backend
    ports:
      - "5002:5002"
    env_file:
      - ./backend/.env
    environment:
      - PORT=5002
      - NODE_ENV=production
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fundsroom-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always
